development: 
  adapter: postgresql
  encoding: unicode
  database: fifth_development
  pool: 5
  username: ubuntu
  password: 

test: 
  adapter: postgresql
  encoding: unicode
  database: fifth_test
  pool: 5
  username: ubuntu
  password: 

production: 
  adapter: postgresql
  encoding: unicode
  database: fifth_production
  pool: 5
  username: ubuntu
  password: